spring:
  datasource:
    username: ENC(5IneQTKBBTx5jbKyAZFTzw==)
    password: ENC(1eXvsINHkVzBa3NzwsniUlhi8DSfe79oEq85rmm9+To=)
    url: ENC(oya2XWciPyO1aJq6zAdGVoN+BVZUXAmi2JiP8TLrQbyevzBEc3ISSxl06hXlGAwCnDHDAsKtMMTSeFNliFreTiVbmcu7pqRn6s8npTg163K3KF2zky6IsKu0Q3rDjN+zt1aXe8jaa7U=)
    driver-class-name: com.mysql.jdbc.Driver
