spring:
  datasource:
    username: ENC(5IneQTKBBTx5jbKyAZFTzw==)
    password: ENC(1eXvsINHkVzBa3NzwsniUlhi8DSfe79oEq85rmm9+To=)
    url: ENC(Qj47iDmMC7tAuF9dTFFBu4gm3mjyPgLcjhuh3NZLqNxCDtU9Exk4Ls7DxsMPq9iZEGtymLyU/7G3V1/CsD57VsHv3RL4L7RnZggML1/8gdn0lWxSC0aDpyuQJaMvest/x6mIhfbyJyZY+gNnaysTidSXVxpMeKOx)
    driver-class-name: com.mysql.cj.jdbc.Driver
