name: depoly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17   
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.2.1
        with:
          gradle-version: 7.4.2
          arguments: build -x test
